import type { Metadata } from "next";
import "../assets/css/index.css";
// import "./globals.css";


export const metadata: Metadata = {
  title: "Intuit Accounts - Sign In",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
